version: '3'

volumes:
  postgres_data:
      driver: local
  keycloak_data:
      driver: local
  meveo_data:
      driver: local
  meveo_binary_data:
      driver: local

services:
  postgres:
      image: manaty/postgres-meveo:latest
      container_name: postgres
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: meveo
        POSTGRES_USER: meveo
        POSTGRES_PASSWORD: meveo
      ports:
        - 5432:5432
  meveo:
      image: manaty/wildfly-meveo:latest
      container_name: meveo
      volumes:
        - keycloak_data:/opt/jboss/wildfly/standalone/data/keycloakdb
        - meveo_data:/opt/jboss/wildfly/meveodata
        - meveo_binary_data:/tmp/meveo/binary/storage
      environment:
        MEVEO_LOG_LEVEL: DEBUG    # default: INFO
      ports:
        - 8080:8080
      depends_on:
        - postgres
