version: '3.5'

volumes:
  postgres_data:
    driver: local
  keycloak_data:
      driver: local
  meveo_data:
      driver: local
  meveo_binary_data:
      driver: local

services:
  postgres:
      image: manaty/postgres-meveo:dev-latest
      container_name: postgres
      networks:
        - meveo
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: meveo
        POSTGRES_USER: meveo
        POSTGRES_PASSWORD: meveo
      ports:
        - 5432:5432
  keycloak:
      image: manaty/keycloak
      container_name: keycloak
      networks:
        - meveo
      restart: unless-stopped
      volumes:
        - keycloak_data:/opt/jboss/keycloak/standalone/data/keycloakdb
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8081:8080
  meveo:
      image: manaty/wildfly-meveo:dev-latest
      container_name: meveo
      networks:
        - meveo
      volumes:
        - meveo_data:/opt/jboss/wildfly/meveodata
        - meveo_binary_data:/tmp/meveo/binary/storage
      environment:
        KEYCLOAK_URL: http://kc-server:8081/auth
      ports:
        - 8080:8080
      depends_on:
        - postgres

networks:
  meveo:
    name: meveo